safe: false
source: .
destination: _site
lsi: false
markdown: rdiscount
pygments: true
permalink: pretty
baseurl: "http://www.candidatometro.cl"
exclude: ['node_modules']

project:
    name: Candidatómetro
